pipeline:
  name: xzcxzv
  identifier: xzcxzv
  projectIdentifier: RajathaTest2
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubrajatha
        build:
          spec:
            branch: main
          type: branch
  stages:
    - stage:
        name: xcvvcx
        identifier: xcvvcx
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      type: Run
                      name: xzvzx
                      identifier: xzvzx
                      spec:
                        connectorRef: account.gcpaccount
                        image: harness/drone-git:1.0.6-rootless-linux-amd64
                        shell: Sh
                        command: |-
                          echo hello
                          #---data---
                          echo 1 
                      timeout: 1m
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Sh
                        command: |-
                          i=0
                          while [ $i -lt 10 ]
                          do
                              df -h
                              du -sh *
                              sleep 10
                              i=`expr $i + 1`
                          done
                        connectorRef: dockerrajatha
                        image: alpine
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.Harness_Kubernetes_Cluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector:
                abc: abc
              os: Linux
  allowStageExecutions: true
  delegateSelectors:
    - ciaccountdelegate
  timeout: 1d
  notificationRules:
    - name: abc
      identifier: abc
      pipelineEvents:
        - type: StageFailed
          forStages:
            - xcvvcx
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - rajatha.ranganath@harness.io
      enabled: true
  variables:
    - name: cookieIdentifier
      type: String
      description: ""
      required: false
      value: <+input>.default( )
