pipeline:
  identifier: Build_testgo_1738062830911
  name: Build testgo
  orgIdentifier: default
  projectIdentifier: ebtasamDevTest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.DhirajGithubv2
        repoName: testgo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "success!"
                  timeout: ""
                  type: Run
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: pod_test_name
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
